services:
  - type: web
    name: medicare-backend-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false

  - type: static
    name: drconnects24-web-portal
    env: static
    rootDir: web-portal
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://medicare-backend-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
