// In-Memory Data Store with persistent helper methods for MediCare+

class DataStore {
  constructor() {
    this.settings = {
      availableCities: ['Jaipur', 'Delhi NCR', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Pune', 'Chennai'],
      consultationLanguages: ['English', 'Hindi', 'Marathi', 'Gujarati', 'Bengali', 'Telugu'],
      platformFee: 49.0,
      gstPercentage: 18.0,
      appName: 'MediCare+',
      contactEmail: 'support@medicareplus.com',
      contactPhone: '+91 1800 123 4567',
      allowNewRegistrations: true,
      maintenanceMode: false,
      activeBanners: [
        {
          id: 'b1',
          title: 'Your Health, Our Priority',
          subtitle: 'Consult qualified doctors 24/7 online',
          cta: 'Consult Now',
          bgGradient: ['#1E3A8A', '#2563EB'],
        },
        {
          id: 'b2',
          title: 'Care Plan 2026',
          subtitle: 'Get 12 FREE Video Consultations',
          cta: 'Activate Plan',
          bgGradient: ['#0284C7', '#06B6D4'],
        },
      ],
    };

    this.coupons = [
      { code: 'HEALTH50', discount: 50.0, minAmount: 200, isActive: true },
      { code: 'MEDICARE100', discount: 100.0, minAmount: 400, isActive: true },
      { code: 'FIRSTFREE', discount: 299.0, minAmount: 299, isActive: true },
    ];

    this.users = [
      {
        id: 'u1',
        name: 'Piyush Prajapati',
        email: 'piyush@example.com',
        phone: '+91 98765 43210',
        role: 'patient',
        status: 'active',
        createdAt: '2026-01-15T10:00:00Z',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
        currentCity: 'Jaipur',
      },
      {
        id: 'u2',
        name: 'Dr. Rajesh Sharma',
        email: 'dr.rajesh@medicare.com',
        phone: '+91 98290 11223',
        role: 'doctor',
        status: 'active',
        doctorId: 'd1',
        createdAt: '2025-11-20T10:00:00Z',
        avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400',
      },
      {
        id: 'u3',
        name: 'System Admin',
        email: 'admin@medicare.com',
        phone: '+91 99000 00000',
        role: 'admin',
        status: 'active',
        createdAt: '2025-10-01T10:00:00Z',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      },
    ];

    this.specialties = [
      {
        id: 's1',
        name: 'General Physician',
        icon: 'medical_services_rounded',
        bgColorHex: '#EBF5FF',
        iconColorHex: '#1A56DB',
        doctorCount: 42,
        description: 'Common illness, fever, cough, flu & general health checkups',
      },
      {
        id: 's2',
        name: 'Dermatologist',
        icon: 'face_retouching_natural_rounded',
        bgColorHex: '#FDF2F8',
        iconColorHex: '#DB2777',
        doctorCount: 28,
        description: 'Skin rash, acne, hair loss & cosmetic consultations',
      },
      {
        id: 's3',
        name: 'Pediatrician',
        icon: 'child_care_rounded',
        bgColorHex: '#ECFDF5',
        iconColorHex: '#059669',
        doctorCount: 35,
        description: 'Infant care, child growth, vaccination & kids illness',
      },
      {
        id: 's4',
        name: 'Gynecologist',
        icon: 'pregnant_woman_rounded',
        bgColorHex: '#FEF3C7',
        iconColorHex: '#D97706',
        doctorCount: 31,
        description: 'Women health, pregnancy care & menstrual wellness',
      },
      {
        id: 's5',
        name: 'Cardiologist',
        icon: 'favorite_rounded',
        bgColorHex: '#FEE2E2',
        iconColorHex: '#DC2626',
        doctorCount: 19,
        description: 'Heart rate, chest pain, hypertension & cardiac health',
      },
      {
        id: 's6',
        name: 'Psychiatrist',
        icon: 'psychology_rounded',
        bgColorHex: '#F3E8FF',
        iconColorHex: '#9333EA',
        doctorCount: 22,
        description: 'Mental health, stress management, anxiety & therapy',
      },
    ];

    this.doctors = [
      {
        id: 'd1',
        name: 'Dr. Rajesh Sharma',
        specialty: 'General Physician',
        qualification: 'MBBS, MD (Internal Medicine)',
        experienceYears: 14,
        experienceText: '14 yrs exp',
        ratingPercentage: 96,
        patientStoriesCount: 420,
        consultationFee: 499,
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400',
        isOnline: true,
        allowsPhysical: true,
        allowsVideo: true,
        isVerified: true,
        verificationStatus: 'approved',
        medicalLicenseNo: 'MCI/2012/88741',
        stateMedicalCouncil: 'Rajasthan Medical Council',
        qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
        clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        clinicName: 'Sharma Health Clinic',
        clinicAddress: 'Malviya Nagar, Jaipur',
        distanceKm: 2.4,
        languages: ['English', 'Hindi'],
        aboutText: 'Dr. Rajesh Sharma is a renowned Senior Consultant Physician with over 14 years of clinical experience in treating acute and chronic lifestyle disorders.',
        services: ['General Health Checkup', 'Diabetes Management', 'Hypertension Treatment', 'Fever & Infection Care'],
      },
      {
        id: 'd2',
        name: 'Dr. Priya Mehta',
        specialty: 'Dermatologist',
        qualification: 'MBBS, DVD, MD (Dermatology)',
        experienceYears: 9,
        experienceText: '9 yrs exp',
        ratingPercentage: 94,
        patientStoriesCount: 310,
        consultationFee: 599,
        imageUrl: 'https://images.unsplash.com/photo-1594824813566-78a933758f46?w=400',
        isOnline: true,
        allowsPhysical: true,
        allowsVideo: true,
        isVerified: true,
        verificationStatus: 'approved',
        medicalLicenseNo: 'DMC/2015/65412',
        stateMedicalCouncil: 'Delhi Medical Council',
        qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
        clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        clinicName: 'Skin & Laser Care Centre',
        clinicAddress: 'C-Scheme, Jaipur',
        distanceKm: 4.1,
        languages: ['English', 'Hindi'],
        aboutText: 'Expert dermatologist specializing in clinical dermatology, anti-aging therapies, acne scars, and laser procedures.',
        services: ['Acne & Scar Treatment', 'Laser Hair Reduction', 'Pigmentation Care', 'Hair Loss Therapy'],
      },
      {
        id: 'd3',
        name: 'Dr. Amit Gupta',
        specialty: 'Pediatrician',
        qualification: 'MBBS, DCH, MD (Pediatrics)',
        experienceYears: 12,
        experienceText: '12 yrs exp',
        ratingPercentage: 98,
        patientStoriesCount: 512,
        consultationFee: 450,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400',
        isOnline: false,
        allowsPhysical: true,
        allowsVideo: true,
        isVerified: true,
        verificationStatus: 'approved',
        medicalLicenseNo: 'RMC/2014/90214',
        stateMedicalCouncil: 'Rajasthan Medical Council',
        qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
        clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        clinicName: 'Little Angels Children Hospital',
        clinicAddress: 'Vaishali Nagar, Jaipur',
        distanceKm: 5.8,
        languages: ['English', 'Hindi'],
        aboutText: 'Dedicated pediatrician providing comprehensive child wellness, growth monitoring, and newborn care.',
        services: ['Newborn Screening', 'Vaccination Schedule', 'Child Nutrition', 'Asthma Care'],
      },
      {
        id: 'd4',
        name: 'Dr. Sneha Verma',
        specialty: 'Gynecologist',
        qualification: 'MBBS, MS (Obstetrics & Gynae)',
        experienceYears: 11,
        experienceText: '11 yrs exp',
        ratingPercentage: 95,
        patientStoriesCount: 280,
        consultationFee: 650,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400',
        isOnline: true,
        allowsPhysical: true,
        allowsVideo: true,
        isVerified: true,
        verificationStatus: 'approved',
        medicalLicenseNo: 'MMC/2016/43981',
        stateMedicalCouncil: 'Maharashtra Medical Council',
        qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
        clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        clinicName: 'Bliss Women Wellness Clinic',
        clinicAddress: 'Raja Park, Jaipur',
        distanceKm: 3.2,
        languages: ['English', 'Hindi'],
        aboutText: 'Specialist in high-risk pregnancies, infertility management, and modern laparoscopic gynecological care.',
        services: ['Antenatal Care', 'PCOS & Hormone Management', 'Infertility Counseling', 'Well-Woman Screening'],
      },
      {
        id: 'd5',
        name: 'Dr. Vikramaditya Rathore',
        specialty: 'Cardiologist',
        qualification: 'MBBS, MD (Internal Medicine), DM (Cardiology)',
        experienceYears: 12,
        experienceText: '12 yrs exp',
        ratingPercentage: 97,
        patientStoriesCount: 190,
        consultationFee: 800,
        imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400',
        isOnline: false,
        allowsPhysical: true,
        allowsVideo: true,
        isVerified: false,
        verificationStatus: 'pending',

        // 1. Basic Info
        phone: '+91 98112 34567',
        altPhone: '+91 94140 12345',
        email: 'dr.vikramaditya@medicare.com',
        gender: 'Male',
        dateOfBirth: '1987-04-12',

        // 2. Licensing & Registration
        medicalLicenseNo: 'RMC/2011/77321',
        stateMedicalCouncil: 'Rajasthan Medical Council',
        registrationState: 'Rajasthan',
        registrationYear: '2011',
        licenseValidTill: '2036',
        subSpecialty: 'Interventional Cardiology & Angiography',
        languages: ['English', 'Hindi', 'Punjabi'],

        // 3. Education
        primaryDegree: 'MBBS',
        primaryCollege: 'SMS Medical College & Hospital, Jaipur',
        primaryPassingYear: '2011',
        postGradDegree: 'MD (Internal Medicine)',
        postGradCollege: 'AIIMS New Delhi',
        postGradPassingYear: '2015',

        // 4 & 5. Clinic & Practice Details
        clinicName: 'Rathore Heart & Multispecialty Clinic',
        clinicAddress: 'Plot 12, JLN Marg, Near World Trade Park, Jaipur, Rajasthan - 302018',
        city: 'Jaipur',
        state: 'Rajasthan',
        pincode: '302018',
        landmark: 'Opposite Gaurav Tower, Malviya Nagar',
        distanceKm: 1.8,
        consultationType: 'both',
        inPersonFee: 800,
        videoFee: 650,
        followUpFee: 400,
        slotDuration: '20 mins',
        availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        availableTimeSlots: ['Morning (09:00 AM - 01:00 PM)', 'Evening (05:00 PM - 09:00 PM)'],
        emergencyAvailable: true,

        // 6. Complete Document Vault Uploads
        medicalCouncilCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
        qualificationCertUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800',
        primaryDegreeCertUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800',
        postGradCertUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800',
        idProofUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
        clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        signatureSpecimenUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800',

        // 7. Bank & Payout Details
        bankName: 'HDFC Bank',
        accountHolder: 'Dr. Vikramaditya Rathore',
        accountNo: '50100492817263',
        ifscCode: 'HDFC0001234',
        upiId: 'drvikram@okhdfcbank',
        panNumber: 'ABCDE1234F',

        aboutText: 'Senior Consultant Interventional Cardiologist specializing in angiography, angioplasty, and cardiac pacing.',
        services: ['ECG & Echo', 'Angiography', 'Hypertension Clinic', 'Pacemaker Check'],
      }
    ];

    this.hospitals = [
      {
        id: 'h1',
        name: 'Manipal Super Specialty Hospital',
        address: 'Sector 5, Vidhyadhar Nagar, Jaipur',
        phone: '+91 141 3988 888',
        rating: 4.8,
        reviewsCount: 1240,
        totalBeds: 350,
        icuBeds: 45,
        verified: true,
        imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
        facilities: ['24/7 Emergency', 'Cardiology ICU', 'Modern OT', 'Radiology & MRI'],
      },
      {
        id: 'h2',
        name: 'Fortis Escorts Hospital',
        address: 'Jawaharlal Nehru Marg, Malviya Nagar, Jaipur',
        phone: '+91 141 2547 000',
        rating: 4.7,
        reviewsCount: 980,
        totalBeds: 280,
        icuBeds: 38,
        verified: true,
        imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600',
        facilities: ['Organ Transplant', 'Trauma Center', 'Dialysis Unit', 'Pharmacy 24/7'],
      },
    ];

    this.appointments = [
      {
        id: 'apt-101',
        userId: 'u1',
        doctorId: 'd1',
        doctor: this.doctors[0],
        type: 'video',
        date: '2026-09-22T10:30:00Z',
        timeSlot: '10:30 AM',
        status: 'upcoming',
        fee: 499,
        platformFee: 49,
        taxes: 98.64,
        totalAmount: 646.64,
        selectedLanguage: 'English',
        createdAt: '2026-09-20T14:30:00Z',
        agoraChannelName: 'medicare_call_apt-101',
      },
      {
        id: 'apt-102',
        userId: 'u1',
        doctorId: 'd2',
        doctor: this.doctors[1],
        type: 'inPerson',
        date: '2026-09-25T11:00:00Z',
        timeSlot: '11:00 AM',
        status: 'upcoming',
        fee: 599,
        platformFee: 49,
        taxes: 116.64,
        totalAmount: 764.64,
        selectedLanguage: 'Hindi',
        createdAt: '2026-09-18T09:15:00Z',
        clinicName: 'Skin & Laser Care Centre',
      },
      {
        id: 'apt-100',
        userId: 'u1',
        doctorId: 'd4',
        doctor: this.doctors[3],
        type: 'video',
        date: '2026-09-10T16:00:00Z',
        timeSlot: '04:00 PM',
        status: 'completed',
        fee: 650,
        platformFee: 49,
        taxes: 125.82,
        totalAmount: 824.82,
        selectedLanguage: 'English',
        createdAt: '2026-09-08T11:00:00Z',
        prescription: 'Tab Paracetamol 650mg BD x 3 days. Drink plenty of warm water.',
      },
    ];

    this.chats = [
      {
        id: 'c1',
        appointmentId: 'apt-101',
        senderId: 'u2',
        senderName: 'Dr. Rajesh Sharma',
        receiverId: 'u1',
        text: 'Hello Piyush! I see your video consultation is scheduled for tomorrow at 10:30 AM. Please keep any recent blood test reports handy.',
        timestamp: '2026-09-20T15:00:00Z',
      },
      {
        id: 'c2',
        appointmentId: 'apt-101',
        senderId: 'u1',
        senderName: 'Piyush Prajapati',
        receiverId: 'u2',
        text: 'Sure Doctor, I will upload them right away. Thank you!',
        timestamp: '2026-09-20T15:05:00Z',
      },
    ];

    this.plans = [
      {
        id: 'plan_starter',
        name: 'Starter Care Pass',
        tagline: 'Ideal for immediate doctor consultation & quick recovery',
        price: 199,
        originalPrice: 499,
        durationDays: 30,
        durationLabel: '1 Month',
        consultationLimit: 3,
        isPopular: false,
        badgeText: 'AFFORDABLE',
        isActive: true,
        features: [
          '3 Video or Audio Consultations with top doctors',
          '24/7 Unlimited Doctor Chat & Follow-ups',
          'Official Digital Prescriptions with instant download',
          '10% Flat Discount on all pharmacy orders',
        ],
      },
      {
        id: 'plan_gold',
        name: 'Gold Family Shield',
        tagline: 'Complete coverage for up to 4 family members',
        price: 699,
        originalPrice: 1999,
        durationDays: 180,
        durationLabel: '6 Months',
        consultationLimit: -1,
        isPopular: true,
        badgeText: 'MOST POPULAR',
        isActive: true,
        features: [
          'Unlimited 24/7 Video & Audio Consultations',
          'Direct connection to MD Specialists & Super-specialists',
          'Family coverage for up to 4 family profiles',
          'Instant Electronic Rx with Priority Pharmacy Dispatch',
          '20% Off all prescribed tablets & medicines',
        ],
      },
      {
        id: 'plan_platinum',
        name: 'Platinum 365 SuperCare',
        tagline: 'Premium VIP medical access & 1-year coverage',
        price: 1299,
        originalPrice: 3499,
        durationDays: 365,
        durationLabel: '1 Year',
        consultationLimit: -1,
        isPopular: false,
        badgeText: 'BEST VALUE',
        isActive: true,
        features: [
          'Unlimited Consultations for the entire year (365 Days)',
          'Dedicated Personal Medical Coordinator & Family Physician',
          'Free Annual Comprehensive Health Package',
          'Flat 25% Off Medicines + Free 2-Hour Express Delivery',
        ],
      },
    ];

    this.subscriptions = [];

    this.wallets = {
      'u1': {
        userId: 'u1',
        balance: 1450.0,
        totalCashbackEarned: 185.0,
        transactions: [
          {
            id: 'tx_101',
            title: 'HealthPay Balance Added',
            description: 'Top-up via UPI (Google Pay)',
            amount: 1000.0,
            isCredit: true,
            category: 'topUp',
            timestamp: '2026-09-22T09:14:00Z',
            referenceId: 'UPI-9841278129',
            status: 'completed',
          },
          {
            id: 'tx_102',
            title: 'Consultation Fee Paid',
            description: 'Paid to Dr. Rajesh Sharma',
            amount: 499.0,
            isCredit: false,
            category: 'consultation',
            timestamp: '2026-09-22T10:30:00Z',
            referenceId: 'MED-CONS-88219',
            status: 'completed',
          },
          {
            id: 'tx_103',
            title: '5% Instant Health Cashback',
            description: 'Rewarded for Telehealth Consultation',
            amount: 25.0,
            isCredit: true,
            category: 'cashback',
            timestamp: '2026-09-22T10:31:00Z',
            referenceId: 'CB-99214',
            status: 'completed',
          },
        ],
      },
    };

    this.diseases = [
      { id: 'dis_1', name: 'Fever & Chills', specialty: 'General Physician', symptomCount: '12 Symptoms' },
      { id: 'dis_2', name: 'Cough, Cold & Flu', specialty: 'General Physician', symptomCount: '8 Symptoms' },
      { id: 'dis_3', name: 'Skin Acne & Pimples', specialty: 'Dermatologist', symptomCount: '6 Symptoms' },
      { id: 'dis_4', name: 'Hair Fall & Dandruff', specialty: 'Dermatologist', symptomCount: '5 Symptoms' },
      { id: 'dis_5', name: 'Child Fever & Vomiting', specialty: 'Pediatrician', symptomCount: '10 Symptoms' },
      { id: 'dis_6', name: 'Pregnancy & Periods', specialty: 'Gynecologist', symptomCount: '14 Symptoms' },
      { id: 'dis_7', name: 'Chest Pain & BP', specialty: 'Cardiologist', symptomCount: '7 Symptoms' },
      { id: 'dis_8', name: 'Anxiety & Depression', specialty: 'Psychiatrist', symptomCount: '9 Symptoms' },
      { id: 'dis_9', name: 'Diabetes Management', specialty: 'General Physician', symptomCount: '11 Symptoms' },
      { id: 'dis_10', name: 'Knee & Joint Pain', specialty: 'Orthopedic', symptomCount: '8 Symptoms' },
    ];

    this.prescriptions = [
      {
        id: 'rx_demo_101',
        consultationId: 'apt-101',
        doctorName: 'Dr. Rajesh Sharma',
        doctorSpecialty: 'General Physician',
        clinicName: 'Sharma Health Clinic',
        doctorRegistrationNumber: 'RMC/2012/88741',
        patientName: 'Piyush Prajapati',
        patientAgeGender: '31 / Male',
        diagnosis: 'Acute Upper Respiratory Tract Infection',
        symptoms: ['Dry cough', 'Mild sore throat', 'Low-grade fever'],
        vitals: {'BP': '120/80 mmHg', 'Pulse': '74 bpm', 'Temp': '99.1 F'},
        clinicalNotes: 'Drink warm water and avoid cold drinks for 5 days.',
        medicines: [
          {
            id: 'm1',
            name: 'Augmentin 625 Duo',
            genericName: 'Amoxicillin + Clavulanic Acid (500mg/125mg)',
            dosage: '1 tablet',
            frequency: 'Twice a day (1-0-1)',
            instructions: 'Immediately after meals',
            durationDays: 5,
            quantity: 10,
            unit: 'Tablets',
            unitPrice: 22.4,
          },
          {
            id: 'm2',
            name: 'Dolo 650',
            genericName: 'Paracetamol (650mg)',
            dosage: '1 tablet',
            frequency: 'Thrice a day as needed (SOS)',
            instructions: 'After food with plenty of water',
            durationDays: 3,
            quantity: 10,
            unit: 'Tablets',
            unitPrice: 3.2,
          },
          {
            id: 'm3',
            name: 'Ascoril D Plus Syrup',
            genericName: 'Dextromethorphan + Chlorpheniramine',
            dosage: '10 ml',
            frequency: 'Bedtime (0-0-1)',
            instructions: 'Do not drink water for 15 mins after syrup',
            durationDays: 5,
            quantity: 1,
            unit: 'Bottle (100ml)',
            unitPrice: 128.0,
          },
        ],
        issuedAt: '2026-09-22T10:45:00Z',
        status: 'issued',
        pharmacyStatus: 'none',
        fulfillmentType: 'none',
        digitalSignatureToken: 'NMC-SIG-88412-V1',
      },
    ];
  }
}

const db = new DataStore();
module.exports = db;
