export const initialUsers = [
  {
    id: 'u1',
    name: 'Piyush Prajapati',
    email: 'piyush@example.com',
    phone: '+91 98765 43210',
    role: 'patient',
    status: 'active',
    createdAt: '2026-01-15T10:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    currentCity: 'Jaipur',
  },
  {
    id: 'u2',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@example.com',
    phone: '+91 98111 22334',
    role: 'patient',
    status: 'active',
    createdAt: '2026-02-10T09:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    currentCity: 'Delhi NCR',
  },
  {
    id: 'u3',
    name: 'Vikram Rathore',
    email: 'vikram.r@example.com',
    phone: '+91 97234 56789',
    role: 'patient',
    status: 'active',
    createdAt: '2026-02-18T14:20:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    currentCity: 'Mumbai',
  },
  {
    id: 'u4',
    name: 'Pooja Patel',
    email: 'pooja.p@example.com',
    phone: '+91 99887 76655',
    role: 'patient',
    status: 'active',
    createdAt: '2026-03-01T11:45:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    currentCity: 'Bengaluru',
  },
  {
    id: 'u5',
    name: 'Dr. Rajesh Sharma',
    email: 'dr.rajesh@drconnects24.com',
    phone: '+91 98290 11223',
    role: 'doctor',
    status: 'active',
    doctorId: 'd1',
    createdAt: '2025-11-20T10:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400',
  },
  {
    id: 'u6',
    name: 'System Admin',
    email: 'admin@drconnects24.com',
    phone: '+91 99000 00000',
    role: 'admin',
    status: 'active',
    createdAt: '2025-10-01T10:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
  },
];

export const initialDoctors = [
  {
    id: 'd1',
    name: 'Dr. Rajesh Sharma',
    specialty: 'General Physician',
    qualification: 'MBBS, MD (Internal Medicine)',
    experienceYears: 14,
    experienceText: '14 yrs exp',
    ratingPercentage: 96,
    patientStoriesCount: 420,
    consultationFee: 499,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400',
    isOnline: true,
    allowsPhysical: true,
    allowsVideo: true,
    isVerified: true,
    verificationStatus: 'approved',
    medicalLicenseNo: 'MCI/2012/88741',
    stateMedicalCouncil: 'Rajasthan Medical Council',
    qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    clinicName: 'Sharma Health Clinic',
    clinicAddress: 'Malviya Nagar, Jaipur',
    distanceKm: 2.4,
    languages: ['English', 'Hindi'],
    aboutText: 'Senior Consultant Physician with over 14 years of clinical experience in treating acute and chronic lifestyle disorders.',
    services: ['General Health Checkup', 'Diabetes Management', 'Hypertension Treatment', 'Fever & Infection Care'],
  },
  {
    id: 'd2',
    name: 'Dr. Priya Mehta',
    specialty: 'Dermatologist',
    qualification: 'MBBS, DVD, MD (Dermatology)',
    experienceYears: 9,
    experienceText: '9 yrs exp',
    ratingPercentage: 94,
    patientStoriesCount: 310,
    consultationFee: 599,
    imageUrl: 'https://images.unsplash.com/photo-1594824813566-78a933758f46?w=400',
    isOnline: true,
    allowsPhysical: true,
    allowsVideo: true,
    isVerified: true,
    verificationStatus: 'approved',
    medicalLicenseNo: 'DMC/2015/65412',
    stateMedicalCouncil: 'Delhi Medical Council',
    qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    clinicName: 'Skin & Laser Care Centre',
    clinicAddress: 'C-Scheme, Jaipur',
    distanceKm: 4.1,
    languages: ['English', 'Hindi'],
    aboutText: 'Expert dermatologist specializing in clinical dermatology, anti-aging therapies, acne scars, and laser procedures.',
    services: ['Acne & Scar Treatment', 'Laser Hair Reduction', 'Pigmentation Care', 'Hair Loss Therapy'],
  },
  {
    id: 'd3',
    name: 'Dr. Amit Gupta',
    specialty: 'Pediatrician',
    qualification: 'MBBS, DCH, MD (Pediatrics)',
    experienceYears: 12,
    experienceText: '12 yrs exp',
    ratingPercentage: 98,
    patientStoriesCount: 512,
    consultationFee: 450,
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400',
    isOnline: false,
    allowsPhysical: true,
    allowsVideo: true,
    isVerified: true,
    verificationStatus: 'approved',
    medicalLicenseNo: 'RMC/2014/90214',
    stateMedicalCouncil: 'Rajasthan Medical Council',
    qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    clinicName: 'Little Angels Children Hospital',
    clinicAddress: 'Vaishali Nagar, Jaipur',
    distanceKm: 5.8,
    languages: ['English', 'Hindi'],
    aboutText: 'Dedicated pediatrician providing comprehensive child wellness, growth monitoring, and newborn care.',
    services: ['Newborn Screening', 'Vaccination Schedule', 'Child Nutrition', 'Asthma Care'],
  },
  {
    id: 'd4',
    name: 'Dr. Sneha Verma',
    specialty: 'Gynecologist',
    qualification: 'MBBS, MS (Obstetrics & Gynae)',
    experienceYears: 11,
    experienceText: '11 yrs exp',
    ratingPercentage: 95,
    patientStoriesCount: 280,
    consultationFee: 650,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400',
    isOnline: true,
    allowsPhysical: true,
    allowsVideo: true,
    isVerified: true,
    verificationStatus: 'approved',
    medicalLicenseNo: 'MMC/2016/43981',
    stateMedicalCouncil: 'Maharashtra Medical Council',
    qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    clinicName: 'Bliss Women Wellness Clinic',
    clinicAddress: 'Raja Park, Jaipur',
    distanceKm: 3.2,
    languages: ['English', 'Hindi'],
    aboutText: 'Experienced gynecologist and obstetrician specializing in maternal health, high-risk pregnancies, and laparoscopic care.',
    services: ['Antenatal Care', 'Fertility Counseling', 'PCOS Management', 'Well Woman Checkup'],
  },
  {
    id: 'd_pending_1',
    name: 'Dr. Vikramaditya Rathore',
    specialty: 'Cardiologist',
    qualification: 'MBBS, MD, DM (Cardiology)',
    experienceYears: 8,
    experienceText: '8 yrs exp',
    ratingPercentage: 100,
    patientStoriesCount: 0,
    consultationFee: 800,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400',
    isOnline: false,
    allowsPhysical: true,
    allowsVideo: true,
    isVerified: false,
    verificationStatus: 'pending',
    medicalLicenseNo: 'RMC/2018/77321',
    stateMedicalCouncil: 'Rajasthan Medical Council',
    qualificationCertUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    idProofUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    clinicAddressProofUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    clinicName: 'Rathore Heart Clinic',
    clinicAddress: 'JLN Marg, Jaipur',
    distanceKm: 1.8,
    languages: ['English', 'Hindi'],
    aboutText: 'Cardiologist with specialized training in preventive cardiology, echocardiography, and hypertension management.',
    services: ['ECG Evaluation', 'Hypertension Control', 'Cholesterol Screening', 'Cardiac Consultation'],
  },
];

export const initialSpecialties = [
  { id: 's1', name: 'General Physician', doctorCount: 42, description: 'Fever, cough, flu & checkups' },
  { id: 's2', name: 'Dermatologist', doctorCount: 28, description: 'Skin, acne, hair & cosmetics' },
  { id: 's3', name: 'Pediatrician', doctorCount: 35, description: 'Child growth, vaccines & kids care' },
  { id: 's4', name: 'Gynecologist', doctorCount: 31, description: 'Women health, pregnancy & care' },
  { id: 's5', name: 'Cardiologist', doctorCount: 19, description: 'Heart, chest pain & cardiac check' },
  { id: 's6', name: 'Psychiatrist', doctorCount: 22, description: 'Mental health & stress therapy' },
];

export const initialHospitals = [
  { id: 'h1', name: 'Apex Super Speciality Hospital', address: 'Malviya Nagar, Jaipur', rating: 4.8, beds: 250, emergency: true },
  { id: 'h2', name: 'Fortis Escorts Hospital', address: 'Jawahar Lal Nehru Marg, Jaipur', rating: 4.9, beds: 310, emergency: true },
  { id: 'h3', name: 'Eternal Heart Care Centre', address: 'Jawahar Circle, Jaipur', rating: 4.7, beds: 180, emergency: true },
];

export const initialAppointments = [
  {
    id: 'apt_101',
    patientName: 'Piyush Prajapati',
    doctorName: 'Dr. Rajesh Sharma',
    specialty: 'General Physician',
    date: '2026-09-24',
    time: '10:30 AM',
    type: 'video',
    status: 'upcoming',
    fee: 499,
  },
  {
    id: 'apt_102',
    patientName: 'Ananya Sharma',
    doctorName: 'Dr. Priya Mehta',
    specialty: 'Dermatologist',
    date: '2026-09-24',
    time: '02:00 PM',
    type: 'inPerson',
    status: 'upcoming',
    fee: 599,
  },
  {
    id: 'apt_103',
    patientName: 'Vikram Rathore',
    doctorName: 'Dr. Sneha Verma',
    specialty: 'Gynecologist',
    date: '2026-09-23',
    time: '11:15 AM',
    type: 'video',
    status: 'completed',
    fee: 650,
  },
];
